stages:
  - build

run script:
  stage: build
  tags:
    - ubuntu
  only:
    changes:
      - 'script.sql'
  script:
    - mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam < $CI_PROJECT_DIR/script.sql